### ISSUE TITLE
npm run back not immediately usable

### ISSUE THREAD

**Issue by merveillevaneck** [mk360/trpc-cra-typescript-template#1]
Hi There! Here are steps to replicate on my end:

- [ ] clone repo
- [ ] install node version lts/hydrogen
- [ ] run `npm run setup`
- [ ] open terminal tab in same dir and run `npm run back`
- [ ] get the following output
```
> back
> cd lib && node .

sh: 1: cd: can't cd to lib
```

I'm sure its a small fix but i just wanted to point out that its not extremely obvious why the `cd lib` step is there. personally i find myself just assuming that it just means to cd into the `lib` folder once the the BE typescript has been compiled? so should only be a readme update at most.

Also not sure what your recommendation is RE setting up scripts for compilation. This could use a nodemon setup for development.

Thanks for the repo btw :) Finding it fun to tinker with while learning trpc. might use something similar in production projects in the future!

**Comment by mk360** [comment]
Hey! Thanks for opening the issue. I'll update the README, and I'll add nodemon. Let me know if it helps clearing things up ^^.

**Comment by mk360** [comment]
@merveillevaneck I'll close the issue for now. Feel free to reopen it if you still find the readme unclear.
